### ISSUE TITLE
403 error occurs after a random amount of time

### ISSUE THREAD

**Issue by Sotatek-GiangBui** [stepanbenes/api-for-nopcommerce#80] opened 2022-10-14 09:04 UTC
I have generated the token from the `/token` endpoint.
I use this token to call other api.

At the client, I store the token locally.
Every time I call the nopcommerce api, I check the '`expiration time`' of the jwt token. If it is not expired then use it, if expired then call api /token.

It worked correctly at first, but after about 8-24 hours, using that token, getting a 403 error.
I use https://jwt.io to check the expiration date, it's still valid.

I haven't found the cause yet, please can u tell me how to fix this issue?
Thankyou

**Comment by D3bo** [comment] 2024-03-05 10:28
Hi, I could not reproduce the error. 

I will close this issue for now becouse i don't think is relevant anymore, but do not esitate to reopen it if you need!

**Closed by D3bo** 2024-03-05 10:28 UTC
Labels: question
